return {
  -- "nvim-neo-tree/neo-tree.nvim",
  -- version = "*",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
  --   "MunifTanjim/nui.nvim",
  -- },
  -- lazy = false,
  -- keys = {
  --   { "\\", ":Neotree reveal<CR>", desc = "NeoTree reveal", silent = true },
  -- },
  -- opts = {
  --   filesystem = {
  --     hijack_netrw_behavior = "open_default",
  --     window = {
  --       mappings = {
  --         ["\\"] = "close_window",
  --       },
  --     },
  --   },
  --   default_component_configs = {
  --     file_size = {
  --       enabled = false,
  --     },
  --     type = {
  --       enabled = false,
  --     },
  --
  --     last_modified = {
  --       enabled = false,
  --     },
  --     created = {
  --       enabled = false,
  --     },
  --   },
  -- },
}
